version: "3"

services:
  rabbitmq:
    image: 'rabbitmq:3.8.27-management-alpine'
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - '5672:5672'
      - '15672:15672'

  myapp:
    build: .
    image: myimage
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
        - "8000:8000"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: ./rabbit_consumer
      dockerfile: Dockerfile
    environment:
      AMQP_HOST: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    restart: always
